# å¯¼èˆªæ èœå•
menu:
  é¦–é¡µ: /
  #  å½’æ¡£:
  #    - æ ‡ç­¾ || /tags
  #    - åˆ†ç±» || /categories
  #    - æ—¥å† || /archives
  æ ‡ç­¾: /tags
  åˆ†ç±»: /categories
  å½’æ¡£: /archives
  ç»Ÿè®¡: /count
  å…³äº: /about
  ç•™è¨€: /contact
  é“¾æ¥:
    - å‹æƒ…é“¾æ¥ || /friends
    - å·¥ä½œç»å† || /journal
favicon: https://images.islu.cn/é—²èŠ±æ‰‹æœ­.jpg

page_count: 15 # é¦–é¡µå±•ç¤ºæ–‡ç« æ•°

darkmode: # æ·±è‰²æ¨¡å¼
  enable: true # æ˜¯å¦å¼€å¯
  starDark: true # æµæ˜ŸèƒŒæ™¯
  setTime: 0||0 # å®šæ—¶å¼€å¯æ·±è‰²æ¨¡å¼ æ™š||æ—©

pjax: true # pjax

tags: true # æ–‡ç« å†…æ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾

header_animation: true # é¦–é¡µåŠ¨ç”»

loading: true # åŠ è½½åŠ¨ç”»

notice: # é¦–é¡µå…¬å‘Š
  style1: true # æ˜¯å¦æ˜¾ç¤º
  style2: false

# ä½ç½®æ»šåŠ¨æç¤ºæ¡
scrollbar:
  footer: true # åº•éƒ¨ä½ç½®æç¤ºæ¡
  aside: true # ä¾§è¾¹ä½ç½®æç¤ºæ¡

# ä¸»é¢˜é¢œè‰²
theme_color:
  main: '#2d78ad' # ä¸»è‰²
  fan: '#00c4b6' # å°é£è½¦
  body_a: '#00c4b6' # å…¨å±€aæ ‡ç­¾é¢œè‰²
  title: '#ff7242' # åšä¸»æ˜µç§°

# è‡ªåŠ¨æˆªå–
index_description:
  line: 1 # æ˜¾ç¤ºå¤šå°‘è¡Œåå‡ºç°çœç•¥å·(...)
  length: 20 # æˆªå–å¤šå°‘å­—

# Whether to display the musics.
# æ˜¯å¦åœ¨é¦–é¡µæ˜¾ç¤ºéŸ³ä¹.
music:
  enable: false
  autoHide: false   # hide automaticaly
  server: tencent #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 7865349211 #require	song id / playlist id / album id / search keyword
  fixed: true      # å¼€å¯å¸åº•æ¨¡å¼
  autoplay: true   # æ˜¯å¦è‡ªåŠ¨æ’­æ”¾
  theme: '#42b983'
  loop: 'all'       # éŸ³é¢‘å¾ªç¯æ’­æ”¾, å¯é€‰å€¼: 'all', 'one', 'none'
  order: 'random'   # éŸ³é¢‘å¾ªç¯é¡ºåº, å¯é€‰å€¼: 'list', 'random'
  preload: 'auto'   # é¢„åŠ è½½ï¼Œå¯é€‰å€¼: 'none', 'metadata', 'auto'
  volume: 0.7        # é»˜è®¤éŸ³é‡ï¼Œè¯·æ³¨æ„æ’­æ”¾å™¨ä¼šè®°å¿†ç”¨æˆ·è®¾ç½®ï¼Œç”¨æˆ·æ‰‹åŠ¨è®¾ç½®éŸ³é‡åé»˜è®¤éŸ³é‡å³å¤±æ•ˆ
  listFolded: false  # åˆ—è¡¨é»˜è®¤æŠ˜å 

# å›¾ç‰‡æ‡’åŠ è½½
lazyload:
  enable: true
  loadimg: http://lcbupayun.test.upcdn.net/static/js/load.gif

# Whether to display the title of the recommended posts
# æ˜¯å¦æ˜¾ç¤ºæ¨èæ–‡ç« çš„æ ‡é¢˜
recommend:
  enable: true
  showTitle: true
  useConfig: false # æ˜¯å¦ä½¿ç”¨é…ç½®æ–‡ä»¶, åœ¨ _data/recommends.json ä¸‹é…ç½®æ¨èæ–‡ç« , falseåˆ™ä¼šèµ°ä¸»é¢˜é…ç½®çš„ top å±æ€§

# éœ€å®‰è£…æ’ä»¶: npm install hexo-generator-search --save
search:
  enable: false # æ˜¯å¦å¯ç”¨æœç´¢
  path: /search.xml
  field: post
  source: http://lcbupayun.test.upcdn.net/js/search.js

# ä»£ç å—é«˜äº®ä¸»é¢˜
highlight_theme: mac # default / darker / pale night / light / ocean / mac / mac light
code_block_expand: # æ˜¯å¦å¼€å¯ä»£ç å—æŠ˜å 
  enable: true
  height: 400 # ä»£ç å—é«˜åº¦è¶…è¿‡400æŠ˜å  å•ä½px
  scrollTop: 200 # å±•å¼€å,å†æ¬¡(æ‰‹åŠ¨ç‚¹å‡»)ç‚¹å‡»æŠ˜å æ»šåŠ¨åˆ°ä»£ç å—å¼€å§‹çš„è·ç¦» å•ä½px

# profile in about _page, including avatars, career, and personal introductions.
# åœ¨â€å…³äºâ€é¡µé¢ä¸­é…ç½®ä¸ªäººä¿¡æ¯ï¼ŒåŒ…æ‹¬å¤´åƒã€èŒä¸šå’Œä¸ªäººä»‹ç».
message:
  avatar: https://images.islu.cn/avatar.jpg # å¤´åƒ
  career: ğŸ“ Javaå…¨æ ˆå·¥ç¨‹å¸ˆ # èŒä¸š
  introduction: ğŸ”” è¿·èŒ«çš„åŸå› å¾€å¾€åªæœ‰ä¸€ä¸ªï¼Œé‚£å°±æ˜¯åœ¨æœ¬è¯¥æ‹¼å‘½å»åŠªåŠ›çš„å¹´çºªï¼Œæƒ³å¾—å¤ªå¤šï¼Œåšå¾—å¤ªå°‘ã€‚ # ä»‹ç»
  mySkills: # æŠ€èƒ½
    enable: true
  myGallery: # ç›¸å†Œ
    enable: false

# æ–‡ç« ç‰ˆæƒ
copyright:
  enable: true
  author: lichongbing
  mail: 873610008@qq.com
  licenses: CC BY-NC-SA 4.0||https://creativecommons.org/licenses/by-nc-sa/4.0/ ## æ–‡ä¸­||ä¸ºåˆ†éš”ç¬¦ï¼Œå·¦ä¾§ä¸ºæè¿°ï¼Œå³ä¾§ä¸ºç‰ˆæƒè®¸å¯
  description: æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨||è®¸å¯åè®®ã€‚è½¬è½½è¯·æ³¨æ˜æ¥è‡ª
  title: è°¦è°¦å›å­

## æ‰“èµ
reward:
  enable: false
  name: è½¯å¦¹å¸ä¸¢ç½®å¤„
  left:
    name: wechat
    img: http://lcbupayun.test.upcdn.net/reward/wechat.png
  right:
    name: alipay
    img: http://lcbupayun.test.upcdn.net/reward/alipay.png


# è¯„è®º
## æ³¨æ„å¤§å°å†™
comments: valine # discuss / twikoo / waline / valine

# mongodb+srv://ialoe:luhuijun123@index.uxhgs.mongodb.net/index?retryWrites=true&w=majority
# mongodb://ialoe:<password>@cluster0-shard-00-00.b8zh3.mongodb.net:27017,cluster0-shard-00-01.b8zh3.mongodb.net:27017,cluster0-shard-00-02.b8zh3.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-rnry28-shard-0&authSource=admin&retryWrites=true&w=majority
# Discuss
## https://discuss.js.org
discuss:
  source: https://cdn.jsdelivr.net/npm/discuss/dist/Discuss.js
  master: åšä¸»
  placeholder: ğŸ¤£ä¸€èµ·æ¥ç©ï¼Œç•™ä¸‹ä½ çš„è¶³è¿¹å§ ~
  serverURLs: https://www.lichongbing.com:6870
  path: location.pathname
  stick: ç½®é¡¶
  visitStat: true
  emotMaps: {
    OwO: {
      type: 'text', items: {
        'å–µæ˜Ÿäºº': '( =â€¢Ï‰â€¢= )m',
        'hi': 'Hi~ o(*ï¿£â–½ï¿£*)ãƒ–',
        'å•Šå•Š': 'w(ï¾ŸĞ”ï¾Ÿ)w',
        'æ“¦çœ¼æ³ª': ' (ãƒã¸ï¿£ã€)',
        'ä¸å±‘': ' (ï¿£_,ï¿£ )',
        'å¥½è€¶': 'ãƒ½(âœ¿ï¾Ÿâ–½ï¾Ÿ)ãƒ',
        'æ£’': ' (à¹‘â€¢Ì€ã…‚â€¢Ì)Ùˆâœ§',
        'æŠ½': '(ï¿£Îµ(#ï¿£)â˜†â•°â•®o(ï¿£çš¿ï¿£///)',
        'äº²': 'ï¼ˆã¥ï¿£3ï¿£ï¼‰ã¥â•­â¤ï½',
        'æ±—': 'Î£( Â° â–³ Â°|||)ï¸´',
        'ç¬¨': '(ï½ï¿£(OO)ï¿£)ãƒ–',
        'æ“¦': 'å‡¸(è‰¹çš¿è‰¹ )',
        'å•µå•µ': '(* ï¿£3)(Îµï¿£ *)',
        'æŒ–é¼»å±': '(*ï¿£rÇ’ï¿£)',
        'å—·': 'â”—|ï½€Oâ€²|â”› å—·~~',
        'é£': 'ï¸¿(ï¿£ï¸¶ï¿£)ï¸¿',
        'å¥½æ»´': '(uâ€¿à¸ºuâœ¿à¸º)',
        'å•¦å•¦': 'â™ª(^âˆ‡^*)',
        'æ‹æ¡Œ': 'o(*â‰§â–½â‰¦)ãƒ„â”â”â”“',
        'æƒŠå–œ': 'â•°(*Â°â–½Â°*)â•¯',
        'å˜Ÿå˜´': 'ï¼ˆâ—‹ï½€ 3â€²â—‹ï¼‰',
        'æ„£ä½': '(Â°ãƒ¼Â°ã€ƒ)',
        'å“¼å“¼': 'o(ï¿£ãƒ˜ï¿£oï¼ƒ)',
        'å´©æºƒ': 'o(â‰§å£â‰¦)o',
        'ä¸æ˜¯æˆ‘': 'ã„Ÿ( â–”, â–” )ã„',
        'å‘ƒå‘ƒå‘ƒ': '(âŠ™ï¹âŠ™)',
        'åˆ‡': '(Ë‰â–½ï¿£ï½) åˆ‡~~',
        'æ‹œæ‹œ': 'ãƒ¾(ï¿£â–½ï¿£)Bye~Bye~',
        'æ–œçœ¼': '( ï¹ ï¹ ) ~â†’',
        'ç¾å‘³': 'Î¨(ï¿£âˆ€ï¿£)Î¨',
        'é—ª': '',
        'âœ§(â‰– â—¡ â‰–âœ¿)': '',
        'æ·¡å®š': '',
        'â”(ï¿£ãƒ¼ï¿£*|||â”â”': '',
        'å¤ªå¯æ€•äº†': 'ãƒ½(*ã€‚>Ğ”<)oã‚œ'
      }
    },
  }

# valine
## https://valine.js.org/
valine:
  enable: true
  appId: tbuq3EDzfQcqA1Tfre173EKh-gzGzoHsz
  appKey: MavVepz0aWA7kfjXPBsC0WNl
  notify: true
  verify: true
  visitor: true
  avatar: 'robohash' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10
  placeholder: 'ğŸ¤£ä¸€èµ·æ¥ç©ï¼Œç•™ä¸‹ä½ çš„è¶³è¿¹å§~(è®°å¾—ç‚¹å‡»éªŒè¯å“¦)ã€‚\nğŸš€æ˜µç§°ä½¿ç”¨QQå·å¯ä»¥è‡ªåŠ¨è¡¥å…¨é‚®ç®±å’Œæ˜¾ç¤ºå¤´åƒæ˜µç§°ç­‰ä¿¡æ¯å‘¢\nğŸ’£è¯·æ–‡æ˜è¯„è®ºå“¦ç¦æ­¢æ¶æ„è¯„è®º' # Comment Box placeholder
  count: true
  enableQQ: true
  recordIP: true
  meta: [ 'nick', 'mail', 'link' ] # è¯„è®ºè€…ç›¸å…³å±æ€§
  requiredFields: [ 'nick','mail' ]
  guest_info: [ 'nick', 'mail', 'link' ]
  master:
    - d382f6b2d7751e5dde9b286d535b977a  # md5åŠ å¯†åçš„åšä¸»é‚®ç®±
    - e6ce4bae9ffac66529ad2694b98f66d3  # md5åŠ å¯†åçš„åšä¸»é‚®ç®±
  metaPlaceholder: # è¾“å…¥æ¡†çš„èƒŒæ™¯æ–‡å­—
    nick: æ˜µç§°/QQå·(å¿…å¡«)
    mail: é‚®ç®±(å¿…å¡«)
    link: ç½‘å€(https://)
  lang: zh-CN
  tagMeta: # The String Array of Words to show Flag.[Just Only xCss Style mode]
    - åšä¸»
    - å°ä¼™ä¼´
    - è®¿å®¢
  friends: # The MD5 String Array of friends Email to show friends Flag.[Just Only xCss Style mode]
    - 2d723b084472eb5c3854616804b4851c # äº‘æ¢¦ â•®ä¸æµ…
    - 68c4c9e1b9a3d34317dc6faefe2ea00e # é˜¿è“
    - ddf016c0f5a3318ea1fc0d20c8ac4429 # ä¸æŸ“è½»è£³
    - 07f6f5a77acec1cf2848d45da1ace3b7 # éƒ­ç¥¥è¿
    - b2ccb12acd9586af59f588e6eda3168c # æœå­é…±
    - d08a0457f664702197dd127bb9a17c2c # itsNekoDeng
    - b52ddf21729e2963a42d5d526808099f # Tajang
    - 5d15e6cd01332d9462562de7eb277133 # Mx
    - aa1a0ae323a0ca99dfb391f9e0ca8565 # Xpand
    - 5e067bcec10c1eca5b744f982156d672 # zhangYHuiâ€™s Blog
    - ac99dc93552427fae0a076d22f6a4ce9 # Huanzã®å°çª
    - 06beff69a2db452d873d6020d1924886 # 51xcode
    - 190004b0922ac4fcd1489fa0aa34663d # å·¦ç¾½

# waline
## https://waline.js.org
waline:
  source: //cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
  serverURL: https://waline.vercel.app/ # æœåŠ¡ç«¯åœ°å€
  placeholder: å¿«æ¥è¯„è®ºå§!! #è¯„è®ºæ¡†å ä½ç¬¦
  avatar: '' # gravatar style https://valine.js.org/#/avatar
  meta: [ 'nick','mail','friends' ] # è¯„è®ºè€…ç›¸å…³å±æ€§
  pageSize: 5 # comment list _page size
  lang: zh-CN # i18n: zh-CN/zh-TW/en/ja
  requiredFields: [ 'nick','mail','friends' ] # è¯„è®ºäººå¿…å¡«é¡¹
  emojiCDN:    # emoji CDN
  emojiMaps:  # è‡ªå®šä¹‰è¡¨æƒ…åŒ…
  option: # è‡ªå®šä¹‰æ·»åŠ  https://waline.js.org/client/basic.html

# twikoo
## https://twikoo.js.org/
twikoo:
  source: https://cdn.jsdelivr.net/npm/twikoo/dist/twikoo.all.min.js
  envId: xxxxxxxx # ä½ çš„ç¯å¢ƒid
  region: ap-shanghai # ç¯å¢ƒåœ°åŸŸï¼Œap-shanghai / ap-guangzhou
  path: window.location.pathname  # ç”¨äºåŒºåˆ†ä¸åŒæ–‡ç« çš„è‡ªå®šä¹‰ js è·¯å¾„ï¼Œå¦‚æœæ‚¨çš„æ–‡ç« è·¯å¾„ä¸æ˜¯ location.pathnameï¼Œéœ€ä¼ æ­¤å‚æ•°
  option:

## è¯´è¯´

# Artitalk
## https://artitalk.js.org/settings.html
artitalk:
  enable: false # æ˜¯å¦å¼€å¯
  source: https://cdn.jsdelivr.net/npm/artitalk
  title: Artitalk # æ ‡é¢˜
  path: artitalk/index.html # è·¯å¾„
  appid: WhOxxxxxxxxxxxxxMMI #  LeanCloud appId
  appkey: M9Pxxxxxxxxxxxxxxx3Kvs # LeanCloud appKey
  serverURL: # å¦‚æœä½ æ˜¯å›½å†…ç‰ˆ LeanCloud ç”¨æˆ·ï¼Œæ­¤é¡¹å¿…å¡«
  lang:  # è¯­è¨€è®¾ç½® é»˜è®¤ä¸­æ–‡ zh / en / es
  atEmoji: # è‡ªå®šä¹‰è¡¨æƒ…åŒ…
  option:

# HPP_talk
## https://hexoplusplus.js.org/
hpp_talk:
  enable: false # æ˜¯å¦å¼€å¯
  source_css: https://cdn.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@9bf1085/talk.css
  source_js: https://cdn.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@9bf1085/talk_user.js
  title: HPP_talk # æ ‡é¢˜
  path: hpp_talk/index.html # è·¯å¾„
  domain: blog.lete114.workers.dev # æ‚¨çš„HexoPlusPlusåŸŸå
  limit: 10 # å•æ¬¡è·å–çš„æœ€å¤šæ¡æ•°
  start: 0 # ä»ç¬¬å‡ æ¡å¼€å§‹
  option:

# 404é¡µé¢
error404:
  enable: true

# 403é¡µé¢
error403:
  enable: true

# é¡µè„š
footer:
  icp:
    enable: true
    text: èœ€ICPå¤‡18037498å·
    icon: http://lcbupayun.test.upcdn.net/static/js/icp.png
    url: https://beian.miit.gov.cn/
  socialLink:
    enable: true
    github: https://github.com/lichongbing
    email: true # é»˜è®¤ä¸ºç‰ˆæƒé‚®ç®±
    facebook: # https://www.facebook.com/xxx
    twitter: # https://twitter.com/xxx
    qq: # 180353980
    weibo: # https://weibo.com/xxx
    zhihu: # https://www.zhihu.com/xxx
    rss: false # trueã€false
    sitemap: true
    upy: true
  # Website start time.
  # ç«™ç‚¹è¿è¡Œå¼€å§‹æ—¶é—´.
  time:
    enable: true
    year: 2017 # å¹´ä»½
    month: 10 # æœˆä»½
    date: 29 # æ—¥æœŸ
    hour: 00 # å°æ—¶
    minute: 00 # åˆ†é’Ÿ
    second: 00 # ç§’

# ç»Ÿè®¡(åˆ†æ)
analytics:
  baidu: # f1685af4772eacc3fcd03ceb5c762abe
  google: # G-XW51H71DB1

# è®¾ç½®å­—ä½“
font:
  # å…¨å±€å­—ä½“
  html: Architects Daughter,cursive
  # ä»£ç å—å­—ä½“
  code: 'Helvetica, Tahoma, Arial, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif'

# ä¸»é¢˜çš„cssä¸jså¼•å…¥
## æ— ç‰¹æ®Šè¦æ±‚è¯·å‹¿æ›´æ”¹
CDN:
  # my resource
  main_css: /css/main.css
  other_css: /css/other.css
  main_js: /js/main.js
  utlis: /js/utlis.js
  pjax: http://lcbupayun.test.upcdn.net/static/js/pjax.min.js
  # fancybox
  fancybox_js: http://lcbupayun.test.upcdn.net/static/js/fancybox.umd.js
  fancybox_css: http://lcbupayun.test.upcdn.net/static/js/fancybox.css
  # åˆ†äº«
  share_css: http://lcbupayun.test.upcdn.net/static/js/share.min.css
  share_js: http://lcbupayun.test.upcdn.net/static/js/share.min.js
  # fontawesome
  fontawesome: http://lcbupayun.test.upcdn.net/static/fontawesome/css/all.min.css
  # ymlè½¬json
  js_yaml: http://lcbupayun.test.upcdn.net/static/js/js-yaml.min.js
  # math
  mathjax: http://lcbupayun.test.upcdn.net/static/js/mathjax.js
